---

- name: Install dnf-automatic package
  ansible.builtin.package:
    name: dnf-automatic
    state: present

- name: Deploy dnf-automatic configuration file
  ansible.builtin.template:
    src: automatic.conf.j2
    dest: /etc/dnf/automatic.conf
    mode: "0644"

- name: Create systemd timer and service files
  block:
    - name: Install dependencies needed for reboot
      ansible.builtin.package:
        name: "{{ dnf_automatic_service_dependencies }}"
        state: present

    - name: Deploy service and timer units
      ansible.builtin.template:
        src: "{{ item }}"
        dest: "/usr/lib/systemd/system/{{ item }}"
        owner: root
        group: root
        mode: "0644"
      loop:
        - dnf-automatic-infrabus.service
        - dnf-automatic-infrabus.timer
      notify: Reload systemd

- name: Check status of dnf-automatic-infrabus.timer
  ansible.builtin.systemd:
    name: dnf-automatic-infrabus.timer
  register: dnf_automatic_infrabus_timer

- name: Set timer state for auto reboot
  ansible.builtin.systemd:
    name: dnf-automatic-infrabus.timer
    state: "{{ dnf_automatic_enable_timer | ternary('started', 'stopped') }}"
    enabled: "{{ dnf_automatic_enable_timer }}"
    masked: false
  # run always if not in check mode and the auto reboot is enabled
  # or if the timer unit exists regardless of the check mode state
  when: (not ansible_check_mode and dnf_automatic_enable_timer) or
        dnf_automatic_infrabus_timer.status["LoadState"] == "loaded"
